modified comment section component & add linter to pre-commit hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,3 +2,9 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 npm run prettier
+npm run lint
+
+if [ $? -ne 0 ]; then
+    echo "Error: Commit failed. Please fix the issues before committing."
+    exit 1
+fi
